# Official Replit configuration for Node.js only
# This replaces any conflicting Python detection

modules = ["nodejs-20", "web"]
run = "npm run dev"
hidden = [".config", ".git", "node_modules", "dist", "archive-python"]

[env]
NODE_ENV = "development"
PORT = "5000"

[deployment]
deploymentTarget = "autoscale"
build = ["node", "build-optimized.js"]
run = ["node", "docker-build-context/dist/index.js"]

[deployment.env]
NODE_ENV = "production"
PORT = "5000"

# Exclude all Python-related content from deployment
[deployment.ignore]
patterns = [
  "*.py",
  "**/*.py", 
  "pyproject.toml",
  "requirements.txt",
  ".pythonlibs/**",
  "archive-python/**",
  ".cache/**",
  ".local/**",
  "attached_assets/**",
  "agents/**",
  "data/**",
  "docs/**",
  "scripts/**"
]

[[ports]]
localPort = 5000
externalPort = 80